version: '3.4'

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - '9092:9092'
    restart: always
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT  # Define el protocolo de seguridad para ambos listeners
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT  # Especifica el nombre del listener interno
    depends_on:
      - zookeeper
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'vaxidrez'
      MYSQL_PASSWORD: 'VaxiDrez2005$$'
      MYSQL_ROOT_PASSWORD: 'VaxiDrez2005$$'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: 'vaxidrez'
      MYSQL_PASSWORD: 'VaxiDrez2005$$'
      MYSQL_ROOT_PASSWORD: 'VaxiDrez2005$$'
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'vaxidrez'
      MONGO_INITDB_ROOT_PASSWORD: 'VaxiDrez2005$$'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://vaxidrez:VaxiDrez2005$@mongodb:27017
      ROOT_URL: http://localhost
      MONGOCLIENT_ENABLE_ADMIN: 'true'
    depends_on:
      - mongodb

volumes:
  mongoclient:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  default:
    name: bankingNetwork
